add_newline = false

format = """
[░▒▓](#a3aed2)\
[ 󰣇 ](bg:#a3aed2 fg:#303446)\
[](bg:#539bf5 fg:#a3aed2)\
$directory\
[](fg:#539bf5 bg:#73799e)\
$git_branch\
$git_status\
[](bg:#565a6e fg:#73799e)\
$nodejs\
$rust\
$golang\
$python\
$php\
[ ](fg:#565a6e)\
\n$character"""

[directory]
style = "fg:#303446  bg:#539bf5"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#00C1FF"
format = '[[ $symbol $branch ](fg:#e9e9ed bg:#73799e)]($style)'

[git_status]
style = "bg:#34548a"
format = '[[$all_status$ahead_behind](fg:#e9e9ed bg:#73799e)]($style)'

[rust]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol ($version) ](fg:#e9e9ed bg:#565a6e)]($style)'

[python]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol ($version \($virtualenv\)) ](fg:#e9e9ed bg:#565a6e)]($style)'

[nodejs]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol ($version) ](fg:#e9e9ed bg:#565a6e)]($style)'
